### ISSUE TITLE
Facing issue when Installing the update

### ISSUE THREAD

**Issue by Sharvin26** [rauc/rauc-hawkbit#15] opened 2019-01-22 08:25 UTC
I am facing the issue when installing an update for my target device. My update is properly downloaded but it fails when Installation process starts.
It Fails at Hawkbit Server console side.
```INFO  Starting installation
    DEBUG    POST https://url//TenantId/controller/v1/controllerId/deploymentBase/..../feedback
    WARNING  Polling failed with a temporary error: g-dbus-error-quark: GDBus.Error:org.
    freedesktop.DBus.Error.ServiceUnknown: The name de.pengutronix.rauc was not provided by 
    any .service files (2)
    INFO     Retry will happen in 60 seconds
```

**Comment by ejoerns** [comment] 2019-01-22 08:34
Seems like the RAUC service is not running on your target.
How did you integrate it? How is it supposed to be started?

You can start the rauc service manually by executing

    rauc service

**Comment by Sharvin26** [comment] 2019-01-22 09:21
I tried that I installed the RAUC service from [https://github.com/rauc/rauc](url) 
How can I check if RAUC is properly configured?
```:~# rauc service
bash: rauc: command not found```

**Comment by Sharvin26** [comment] 2019-01-22 10:09
After executing ` rauc service ` I am getting the following output
` Failed to obtain name de.pengutronix.rauc `

**Comment by ejoerns** [comment] 2019-01-22 10:13
@Sharvin26 If you want to use it for the target, you need to have D-Bus ready and configured.

I highly recommend not doing all these thing manually but using a build system such as Yocto, Buildroot or PTXdist instead.

For doing things manually on the target, you also need a little more than just building RAUC. Probably you should read https://rauc.readthedocs.io/en/latest/integration.html#d-bus-integration. There is also a section for D-Bus integration: https://rauc.readthedocs.io/en/latest/integration.html#d-bus-integration

If you want to keep D-Bus out for the first try, you can configure it using `--disable-service` option.

**Comment by Sharvin26** [comment] 2019-01-22 11:32
I read the [https://rauc.readthedocs.io/en/latest/integration.html#d-bus-integration](url) .
According to the documentation
> properly install the D-Bus service file de.pengutronix.rauc.service

How can I install the service?

**Comment by ejoerns** [comment] 2019-01-22 11:49
Well, when being on the target, you can simply use default automake handling by running `make install` which will install these files properly on your *target* (when being root!).

When on the host, simply use `DESTDIR`:

    make rauc
    mkdir install
    make DESTDIR=$(readlink -f install/) install

Then copy the directory structure in install/ to your target.

This is default autotools/make usage:
https://www.gnu.org/prep/standards/html_node/DESTDIR.html

**Comment by Sharvin26** [comment] 2019-01-22 12:11
Actually, for the Host, I am using Bosch IoT Suite Rollout and for the target, I am using a raspberry pi.
I followed the URL [https://github.com/rauc/rauc-hawkbit](url) But I faced an issue
```
  DEBUG    POST https://url//TenantId/controller/v1/controllerId/deploymentBase/..../feedback
  WARNING  Polling failed with a temporary error: g-dbus-error-quark: GDBus.Error:org.
  freedesktop.DBus.Error.ServiceUnknown: The name de.pengutronix.rauc was not provided by 
  any .service files (2)
  INFO     Retry will happen in 60 seconds
```
After debugging I found that my system is missing rauc installer So I followed this documentation [https://github.com/rauc/rauc](url).
After following the documentation till **Building from Sources** I tried the command 
` rauc service `
And ended up with the error
` Failed to obtain name de.pengutronix.rauc `

**Comment by ejoerns** [comment] 2019-01-22 12:53
Is that by design that all your links are broken?

Nice summary, but.. why?

**Comment by Sharvin26** [comment] 2019-01-22 13:06
By links, do you mean the API calls that are interacting with the Bosch IoT Rollout Service?
All my API calls are working fine for example Device Polling I am getting my deployment base. Using the deployment base it retrieves the download URL  and using that URL it downloads the data successfully then on the console I get the following output :
```
    INFO     Starting installation
    DEBUG    POST 
     https://<URL>//<TennantID>/controller/v1/<ControllerId>/deploymentBase/<...>/feedback
    WARNING  Polling failed with a temporary error: g-dbus-error-quark: GDBus.Error:org.
    freedesktop.DBus.Error.ServiceUnknown: The name de.pengutronix.rauc was not provided by 
    any .service files (2)
```

And All my dbus services are working fine on my raspberry pi.
`systemctl status dbus`
```
   Loaded: loaded (/lib/systemd/system/dbus.service; static; vendor preset: enabled)
   Active: active (running) since Tue 2019-01-22 11:12:23 UTC; 1h 52min ago
```

Error I am getting when running this program is:
```
Traceback (most recent call last):
  File "./rauc-hawkbit-client", line 89, in <module>
    loop.run_until_complete(main())
  File "/raucHawkbit/lib/python3.5/site-packages/gbulb-0.6.1-py3.5.egg/gbulb/glib_events.py", line 736, in run_until_complete
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "./rauc-hawkbit-client", line 82, in main
    result_callback, step_callback)
  File "/raucHawkbit/lib/python3.5/site-packages/rauc_hawkbit-0.1.1.dev2+g7abb898-py3.5.egg/rauc_hawkbit/rauc_dbus_ddi_client.py", line 47, in __init__
    self.rauc = self.new_proxy('de.pengutronix.rauc.Installer', '/')
  File "/raucHawkbit/lib/python3.5/site-packages/rauc_hawkbit-0.1.1.dev2+g7abb898-py3.5.egg/rauc_hawkbit/dbus_client.py", line 68, in new_proxy
    object_path, interface, None)
GLib.Error: g-io-error-quark: Error calling StartServiceByName for de.pengutronix.rauc: Timeout was reached (24)
```
And for Running ` rauc service `
```
Failed to obtain name de.pengutronix.rauc
```
As you told I tried 
` ./configure --disable-service `
It's working for my command line but fails when executing this program.

**Comment by ejoerns** [comment] 2019-01-23 11:48
No, I was talking about the link targets in the issue itself.

For sure, `--disable-service``disables D-Bus support.

Will close this as you reopened as https://github.com/rauc/rauc/issues/396

**Closed as completed by ejoerns** 2019-01-23 11:48 UTC
Labels: help wanted
